/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ColorTheme = IDL.Variant({
  'dark' : IDL.Null,
  'light' : IDL.Null,
  'colorful' : IDL.Null,
});
export const SpeedUnit = IDL.Variant({ 'kph' : IDL.Null, 'mph' : IDL.Null });
export const Settings = IDL.Record({
  'colorTheme' : ColorTheme,
  'speedUnit' : SpeedUnit,
  'speedometerSkin' : IDL.Text,
});

export const idlService = IDL.Service({
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'resetSettings' : IDL.Func([], [], []),
  'setSettings' : IDL.Func([Settings], [], []),
  'toText' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ColorTheme = IDL.Variant({
    'dark' : IDL.Null,
    'light' : IDL.Null,
    'colorful' : IDL.Null,
  });
  const SpeedUnit = IDL.Variant({ 'kph' : IDL.Null, 'mph' : IDL.Null });
  const Settings = IDL.Record({
    'colorTheme' : ColorTheme,
    'speedUnit' : SpeedUnit,
    'speedometerSkin' : IDL.Text,
  });
  
  return IDL.Service({
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'resetSettings' : IDL.Func([], [], []),
    'setSettings' : IDL.Func([Settings], [], []),
    'toText' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };