/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Settings {
    colorTheme: ColorTheme;
    speedUnit: SpeedUnit;
    speedometerSkin: string;
}
export enum ColorTheme {
    dark = "dark",
    light = "light",
    colorful = "colorful"
}
export enum SpeedUnit {
    kph = "kph",
    mph = "mph"
}
export interface backendInterface {
    getSettings(): Promise<Settings>;
    resetSettings(): Promise<void>;
    setSettings(newSettings: Settings): Promise<void>;
    toText(): Promise<string>;
}
import type { ColorTheme as _ColorTheme, Settings as _Settings, SpeedUnit as _SpeedUnit } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_Settings_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_Settings_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetSettings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSettings();
            return result;
        }
    }
    async setSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSettings(to_candid_Settings_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSettings(to_candid_Settings_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toText(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.toText();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toText();
            return result;
        }
    }
}
function from_candid_ColorTheme_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorTheme): ColorTheme {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Settings_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Settings {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SpeedUnit_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpeedUnit): SpeedUnit {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorTheme: _ColorTheme;
    speedUnit: _SpeedUnit;
    speedometerSkin: string;
}): {
    colorTheme: ColorTheme;
    speedUnit: SpeedUnit;
    speedometerSkin: string;
} {
    return {
        colorTheme: from_candid_ColorTheme_n3(_uploadFile, _downloadFile, value.colorTheme),
        speedUnit: from_candid_SpeedUnit_n5(_uploadFile, _downloadFile, value.speedUnit),
        speedometerSkin: value.speedometerSkin
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
} | {
    colorful: null;
}): ColorTheme {
    return "dark" in value ? ColorTheme.dark : "light" in value ? ColorTheme.light : "colorful" in value ? ColorTheme.colorful : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kph: null;
} | {
    mph: null;
}): SpeedUnit {
    return "kph" in value ? SpeedUnit.kph : "mph" in value ? SpeedUnit.mph : value;
}
function to_candid_ColorTheme_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorTheme): _ColorTheme {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Settings_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Settings): _Settings {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SpeedUnit_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpeedUnit): _SpeedUnit {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorTheme: ColorTheme;
    speedUnit: SpeedUnit;
    speedometerSkin: string;
}): {
    colorTheme: _ColorTheme;
    speedUnit: _SpeedUnit;
    speedometerSkin: string;
} {
    return {
        colorTheme: to_candid_ColorTheme_n9(_uploadFile, _downloadFile, value.colorTheme),
        speedUnit: to_candid_SpeedUnit_n11(_uploadFile, _downloadFile, value.speedUnit),
        speedometerSkin: value.speedometerSkin
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorTheme): {
    dark: null;
} | {
    light: null;
} | {
    colorful: null;
} {
    return value == ColorTheme.dark ? {
        dark: null
    } : value == ColorTheme.light ? {
        light: null
    } : value == ColorTheme.colorful ? {
        colorful: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpeedUnit): {
    kph: null;
} | {
    mph: null;
} {
    return value == SpeedUnit.kph ? {
        kph: null
    } : value == SpeedUnit.mph ? {
        mph: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
